name: MineStats
version: '1.0-SNAPSHOT'
main: me.siraphop.mineStats.MineStats
api-version: '1.21'
load: STARTUP
authors: [ FujaTying ]
description: A simple server stats for Minecraft server
website: https://github.com/FujaTyping/MineStatus
commands:
  mstats:
    description: Displays server resource usage
    usage: /mstats
    permission: mstats.view
  mdstats:
    usage: /mdstats [actionbar/tab/off]
    description: Show server stats
    permission: mstats.setdisplay
permissions:
  mstats.view:
    description: Allows viewing server resource usage
    default: true
  mstats.setdisplay:
    description: Allows set position of viewing server resource usage
    default: true